interface MemberProfile {
  name: string;
  role: string;
  bio: string;
  imageUrl: string;
  hobbies: string;
  dreams: string;
  motto: string;
  favoriteFood: string;
  classMessage: string;
  classGoals: string;
  infoTambahan?: string;
}

export const members: MemberProfile[] = [
  {
    name: "Reica Enggel Lina",
    role: "Calon Pegawai BUMN/Internasional",
    bio: "Melukis. Bercita-cita bekerja di BUMN atau perusahaan internasional.",
    imageUrl: "/members/reica.jpg",
    hobbies: "Melukis",
    dreams: "Bekerja di bumn atau di perusahaan internasional",
    motto: "Jangan berhenti untuk impianmu meski banyak badai besar yang datang",
    favoriteFood: "Jus Alpukat",
    classMessage: "Semoga kita bisa melewati susah senangnya kuliah bersama sama",
    classGoals: "Bisa mewujudkan impian dan cita-cita",
  },
  {
    name: "Ilham Rayyan",
    role: "Hengker",
    bio: "Bola. Ingin menjadi Hengker.",
    imageUrl: "/members/rayyan.png",
    hobbies: "Bola",
    dreams: "Hengker",
    motto: "Islam agamaku",
    favoriteFood: "Hehe",
    classMessage: "indonesia maju",
    classGoals: "indonesia maju",
  },
  {
    name: "Dimas Agung Subayu",
    role: "Programer 2 digit",
    bio: "Nonton. Ingin menjadi Programmer berpenghasilan 2 digit.",
    imageUrl: "/members/dimas.png",
    hobbies: "Nonton",
    dreams: "Programer 2 digit",
    motto: "Selesaikan apa yang sudah di mulai",
    favoriteFood: "Surya",
    classMessage: "Tetap kompak, saling menghormati, dan jadikan kelas ini sebagai rumah kedua yang penuh kebaikan dan kebahagiaan!",
    classGoals: "Lulus tepat waktu",
  },
  {
    name: "Muhammad Fattan Attaur Rahman",
    role: "Calon Game Developer",
    bio: "Ngegame. Bercita-cita menjadi game developer.",
    imageUrl: "/members/fatan.png",
    hobbies: "Ngegame",
    dreams: "Game developer",
    motto: "Perbuatan kecil di masa lalu dapat berpengaruh besar di masa depan",
    favoriteFood: "Kopi",
    classMessage: "Bisa tetap kompak sampe semester akhir",
    classGoals: "Lulus bareng",
  },
  {
    name: "Rizky Syatria",
    role: "Programmer Handal",
    bio: "Bermain Rhythm Game, Menjelajahi Galaxy",
    imageUrl: "/members/rizky-syatria.png",
    hobbies: "Bermain Rhythm Game, Menjelajahi Galaxy",
    dreams: "Menjadi Programmer Handal Namun Enggan Mengoding",
    motto: "Jika tidak ada bahu untuk bersandar, masih ada telur untuk di dadar. Utamakan sarapan, bukan harapan.",
    favoriteFood: "Sate ayam dan Soft drink",
    classMessage: "Bismillah bisa lulus semuanya tepat waktu!",
    classGoals: "Bisa lulus 3.5 tahun tentunya!",
  },
  {
    name: "Fitriani",
    role: "Calon Pengusaha Tambang",
    bio: "Menonton & Membaca. Ingin menjadi pengusaha tambang.",
    imageUrl: "/members/fitriani.jpg",
    hobbies: "Menonton & Membaca",
    dreams: "Menjadi pengusaha tambang",
    motto: "Hasbunallah wani mal wakil ni mal maula wani'man nasir",
    favoriteFood: "Indomie goreng & Gado-gado buatan ibuk",
    classMessage: "Harus tetap kompak walau udah semester akhir",
    classGoals: "Wisuda bareng sekelas dengan predikat cumlaude",
  },
  {
    name: "Meylinda Pratiwi",
    role: "Calon Orang Sukses",
    bio: "Menonton drakor/dracin. Bercita-cita menjadi orang sukses.",
    imageUrl: "/members/meylinda.png",
    hobbies: "Menonton drakor/dracin",
    dreams: "Impian menjadi orang yang sukses kedepannya",
    motto: "Orang bisa, kita harus bisa",
    favoriteFood: "Thaitea",
    classMessage: "Semoga selalu kompak",
    classGoals: "Kesuksesan",
  },
  {
    name: "Muhammad Raja",
    role: "Calon Programmer",
    bio: "Travelling. Ingin menjadi programmer.",
    imageUrl: "members/raja.png",
    hobbies: "Travelling",
    dreams: "Programmer",
    motto: "Cita-cita boleh pudar, S.Kom harus dikejar",
    favoriteFood: "Es bakso",
    classMessage: "Semakin maju dan solid",
    classGoals: "Lulus tepat waktu bersama",
  },
  {
    name: "Eriel Budiman",
    role: "Calon Orang Sukses",
    bio: "Sering ke Kos Nicco. Ingin sukses.",
    imageUrl: "/members/eriel.png",
    hobbies: "Ke Kos Nicco",
    dreams: "Sukses",
    motto: "Tindakan lebih berbicara daripada kata-kata",
    favoriteFood: "Ayam Geprek, Pop Ice",
    classMessage: "Makin Solid",
    classGoals: "Sukses bareng",
  },
  {
    name: "Mitra Asindu",
    role: "Calon Lulusan Terbaik",
    bio: "Mendengar musik di Spotify. Target: Lulus Sarjana tepat waktu.",
    imageUrl: "/members/mitra.png",
    hobbies: "Mendengar musik di Spotify",
    dreams: "Lulus Sarjana Tepat Waktu!",
    motto: "Jalani, perbaiki, dan berusaha memberikan yang terbaik kepada semua orang",
    favoriteFood: "Bread and Avocado Juice",
    classMessage: "Ya tetap kompak, mendukung satu sama lain meskipun nanti semester 5 ada yang lanjut di PSI, DTA, & SIA",
    classGoals: "Lulus Sarjana bareng-bareng satu kelas",
  },
  {
    name: "Adib Muhammad Maros",
    role: "Calon Software Engineer",
    bio: "hidup sekali, hidup yang berarti!",
    imageUrl: "/members/adib.jpeg",
    hobbies: "Baca Buku, Ngoding, Nulis, Coba hal baru",
    dreams: "Software Engineer!",
    motto: "Cintailah takdirmu!",
    favoriteFood: "Ayam Goreng, pecel lele",
    classMessage: "semoga bisa menciptakan kenangan indah yang bisa dikenang di masa depan nantinya",
    classGoals: "Sukses bareng bareng satu kelas",
  },
  {
    name: "Fatimah Tri Zahara",
    role: "Pramugari",
    bio: "Menonton. Bercita-cita menjadi pramugari.",
    imageUrl: "/members/fatimah.jpeg",
    hobbies: "menonton",
    dreams: "pramugari",
    motto: "walaupun di sakiti harus tetap baik",
    favoriteFood: "leci tea",
    classMessage: "saling membantu",
    classGoals: "wisuda bareng",
  },
  {
    name: "M. Iqbal Hakim",
    role: "Desain Grafis",
    bio: "Desainer grafis yang menjunjung optimisme",
    imageUrl: "/members/iqbal.png",
    hobbies: "Desain grafis",
    dreams: "Mencapai puncak impian",
    motto: "Jangan rusak kebahagiaan mu sekarang oleh masa lalu dan kerisauan tentang masa depan",
    favoriteFood: "Bakso dan es teh",
    classMessage: "Semoga bertemu lagi di puncak impian",
    classGoals: "Terus berkomunikasi dimanapun dan kapanpun",
  },
  {
    name: "Rahmat Hidayat",
    role: "Merenungkapanpun",
    bio: "Seseorang yang suka merenung dan mencari makna",
    imageUrl: "/members/rahmat.jpg",
    hobbies: "Merenung",
    dreams: "Mencari jati diri",
    motto: "I think about dying but I don't want to die. Not even close. In fact, my problem is the complete opposite. I want to live, I want to escape. - Matty Healy",
    favoriteFood: "Matcha latte",
    classMessage: "Semoga kalian sehat",
    classGoals: "Bisa memenuhi ekspetasi orang terdekat",
  },
  {
    name: "M. Ajie Saputra",
    role: "Outdoor Enthusiast",
    bio: "Pecinta alam dan pendaki gunung",
    imageUrl: "/members/ajie.png",
    hobbies: "Naik gunung/ke alam",
    dreams: "Youtubers/Presiden",
    motto: "Terimalah perjalanan ini, bermimpi besar bekerja keras",
    favoriteFood: "Ayam Kampung dan Air Putih",
    classMessage: "Kompak dan Solid selalu",
    classGoals: "Duit",
  },
  {
    name: "Aishwarya Rai",
    role: "WFH",
    bio: "Menari dengan semangat",
    imageUrl: "/members/aish.jpg",
    hobbies: "Menari",
    dreams: "WFH",
    motto: "Life goes on",
    favoriteFood: "Makanan pedas, ice cream, coklat, dan matchaa",
    classMessage: "Sukses bareng dunia akhirat ya mantemann❤",
    classGoals: "Meraih kesuksesan dengan impian masing-masing dan membuat kenangan yang baik/bermakna untuk cerita masa depan kelak",
  },
  {
    name: "Nicco Roland",
    role: "Pembelajar",
    bio: "Fokus pada pembelajaran dan literasi",
    imageUrl: "/members/nicco.png",
    hobbies: "Belajar dan membaca",
    dreams: "Triliuner",
    motto: "Tidak perlu terlihat terang, karna kita sudah hitam",
    favoriteFood: "Apa aja yang penting makan minumnya sama kamu",
    classMessage: "Tetep semangat, jangan menyerah nanti tuhan kasih yg mantap2",
    classGoals: "Emm gatau hhe",
  },
  {
    name: "Fauzan Aziman Putra",
    role: "Programmer, pengusaha",
    bio: "Kebaikan adalah investasi terbaik",
    imageUrl: "/members/aziman.png",
    hobbies: "Bola, game",
    dreams: "Sukses di usia muda, bisa open lowongan kerja",
    motto: "Kebaikan adalah investasi terbaik",
    favoriteFood: "Nasi goreng",
    classMessage: "Lulus bareng",
    classGoals: "Lulus bareng",
  },
];
